"""add fts_vector and content_hash to documents

Revision ID: 2b448502c14b
Revises: 5eda65639629
Create Date: 2026-05-16 15:29:48.912137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b448502c14b'
down_revision: Union[str, Sequence[str], None] = '5eda65639629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('fts_vector', postgresql.TSVECTOR(), nullable=True))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint('uq_kb_content_hash', 'documents', ['knowledge_base_id', 'content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_kb_content_hash', 'documents', type_='unique')
    op.drop_column('documents', 'content_hash')
    op.drop_column('chunks', 'fts_vector')
    # ### end Alembic commands ###
